# IKT215 Exercise 1: Preprocessing Data for a Pattern Recognition System

the client has 
-  historical ovacado prices
- and sales
in the US market

they want this data and predictive models to gain a competetive edge

intrested in
- prices of ovacados
- no. of ovacados sold

Data:
- prices and sales data
- feature explanations

In [71]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os
import sys

In [ ]:

DATA_LOCATION = os.path.join(os.path.dirname(os.getcwd()), 'data')
RAW_LOCATION = os.path.join(DATA_LOCATION, 'raw')
RAW_LOCATION

'/Users/valiantlynx/projects/pattern-recognition/data/raw'

In [20]:
prices_and_sales_df = pd.read_csv(os.path.join(RAW_LOCATION, 'price-and-sales-data.csv'))
features_df = pd.read_excel(os.path.join(RAW_LOCATION, 'feature-explanations.xlsx'))

In [25]:
features_df.head()

   Unnamed: 0    Unnamed: 1                                         Unnamed: 2
0         NaN       Feature                                       Explanation
1         NaN          Date  Date of last day (a sunday) in the given week ...
2         NaN  AveragePrice                        Per unit (per avocado) cost
3         NaN  Total Volume                      Total number of avocados sold
4         NaN          4046  Total number of avocados with PLU (Product Loo...

In [23]:
prices_and_sales_df.sample(10)

,Date,AveragePrice,TotalVolume,4046,4225,4770,TotalBags,SmallBags,LargeBags,XLargeBags,type,year,region
13178,2017-05-07,1.09,121483.27,60550.46,3285.18,9701.89,47945.74,45880.43,NaN,9.97,conventional,2017,Boise
23786,2019-04-21,1.51,4530588.27,277991.72,2691950.24,30835.95,1529810.36,1186740.09,342666.94,403.33,conventional,2019,Northeast
18285,2018-04-01,1.16,2122698.81,806170.63,649784.01,9332.56,657411.61,602960.19,53739.39,712.03,conventional,2018,Plains
15042,2017-09-03,1.20,727912.24,407081.82,136998.12,5005.72,178826.58,109254.62,66904.18,2667.78,conventional,2017,PhoenixTucson
19218,2018-05-27,1.27,8557.45,115.44,445.33,0.00,7996.68,7976.68,20.00,0.00,organic,2018,Tampa
5227,2015-12-06,0.81,726504.61,117507.93,NaN,9120.48,380463.57,380298.38,0.00,165.19,conventional,2015,Seattle
15300,2017-09-17,NaN,5487.10,1148.88,131.26,0.00,4206.96,4200.29,6.67,0.00,organic,2017,LasVegas
2510,2015-06-14,1.03,172302.47,103389.69,NaN,7010.57,44678.04,38948.35,NaN,0.00,conventional,2015,Nashville
17785,2018-02-25,1.74,90985.40,10382.97,35406.21,0.00,45196.22,45169.68,26.54,0.00,organic,2018,LosAngeles
17833,2018-03-04,1.21,289090.98,65788.57,130046.74,150.90,93104.77,82676.57,8658.20,1770.00,conventional,2018,HarrisburgScranton

In [24]:
prices_and_sales_df.head(10)

,Date,AveragePrice,TotalVolume,4046,4225,4770,TotalBags,SmallBags,LargeBags,XLargeBags,type,year,region
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.00,conventional,2015,Albany
1,2015-01-04,1.00,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.00,conventional,2015,Atlanta
2,2015-01-04,NaN,788025.06,53987.31,552906.04,39995.03,141136.68,137146.07,3990.61,0.00,conventional,2015,BaltimoreWashington
3,2015-01-04,1.01,80034.32,44562.12,24964.23,2752.35,7755.62,6064.30,1691.32,0.00,conventional,2015,Boise
4,2015-01-04,1.02,491738.00,7193.87,396752.18,128.82,87663.13,87406.84,256.29,0.00,conventional,2015,Boston
5,2015-01-04,1.40,116253.44,3267.97,55693.04,109.55,57182.88,57182.88,0.00,0.00,conventional,2015,BuffaloRochester
6,2015-01-04,0.93,5777334.90,2843648.26,2267755.26,137479.64,528451.74,477193.38,47882.56,3375.80,conventional,2015,California
7,2015-01-04,1.19,166006.29,29419.03,47220.75,38568.95,50797.56,NaN,NaN,0.00,conventional,2015,Charlotte
8,2015-01-04,1.11,783068.03,30270.26,550752.19,124506.10,77539.48,72888.46,4651.02,0.00,conventional,2015,Chicago
9,2015-01-04,0.88,228569.58,3274.30,168764.78,1447.06,NaN,17525.31,37445.46,112.67,conventional,2015,CincinnatiDayton

In [26]:
prices_and_sales_df.tail(10)

,Date,AveragePrice,TotalVolume,4046,4225,4770,TotalBags,SmallBags,LargeBags,XLargeBags,type,year,region
25151,2019-07-14,1.92,18388.22,211.67,3988.14,17.97,14170.44,11680.25,2490.19,0.00,organic,2019,SouthCarolina
25152,2019-07-14,1.59,135850.62,13396.57,2768.15,4263.07,115422.83,108024.40,7398.43,0.00,organic,2019,SouthCentral
25153,2019-07-14,1.61,121947.41,1868.33,12203.15,20.34,107855.59,86169.59,21686.00,0.00,organic,2019,Southeast
25154,2019-07-14,2.46,5032.63,121.45,1306.08,0.00,3605.10,806.67,2798.43,0.00,organic,2019,Spokane
25155,2019-07-14,2.19,6863.87,56.21,3637.63,5.92,3164.11,3155.89,8.22,0.00,organic,2019,StLouis
25156,2019-07-14,1.66,4007.93,218.47,252.29,0.00,3537.17,1460.65,2076.52,0.00,organic,2019,Syracuse
25157,2019-07-14,1.06,3767.89,129.01,0.00,0.00,3638.88,3635.55,3.33,0.00,organic,2019,Tampa
25158,2019-07-14,1.99,1236969.18,106370.49,209820.63,5606.10,915082.38,667494.94,247562.25,25.19,organic,2019,TotalUS
25159,2019-07-14,2.33,209408.22,23918.57,42432.02,985.67,142071.96,75883.13,66163.64,25.19,organic,2019,West
25160,2019-07-14,1.84,16372.24,1195.71,681.10,2765.31,11730.12,10861.33,868.79,0.00,organic,2019,WestTexNewMexico

In [28]:
prices_and_sales_df.shape

(25161, 13)

In [31]:
# their data types and names
prices_and_sales_df.dtypes

Date             object
AveragePrice    float64
TotalVolume     float64
4046            float64
4225            float64
4770            float64
TotalBags       float64
SmallBags       float64
LargeBags       float64
XLargeBags      float64
type             object
year              int64
region           object
dtype: object

In [32]:
prices_and_sales_df.isnull().sum()

Date              0
AveragePrice    902
TotalVolume     949
4046            900
4225            906
4770            916
TotalBags       890
SmallBags       934
LargeBags       947
XLargeBags      868
type              0
year              0
region            0
dtype: int64

In [38]:
# Statistical overview - select only numeric columns. not date etc.
numeric_df = prices_and_sales_df.select_dtypes(include='number')
desc = numeric_df.describe()

# CV = (std / mean) * 100
cv_percent = (numeric_df.std() / numeric_df.mean()) * 100
variance_percent = (numeric_df.var() / (numeric_df.mean() ** 2)) * 100

# Add a new row named 'CV (%)' to the 'desc' DataFrame using .loc[]
desc.loc['Coefficient of Variation (%)'] = cv_percent
desc.loc['Variance (%)'] = variance_percent

desc

,AveragePrice,TotalVolume,4046,4225,4770,TotalBags,SmallBags,LargeBags,XLargeBags,year
count,24259.000000,2.421200e+04,2.426100e+04,2.425500e+04,2.424500e+04,2.427100e+04,2.422700e+04,2.421400e+04,24293.000000,25161.000000
mean,1.396018,9.170913e+05,2.981530e+05,2.958284e+05,2.246362e+04,2.950432e+05,2.124199e+05,7.589924e+04,4405.638467,2016.776877
std,0.384476,3.731937e+06,1.288583e+06,1.209445e+06,1.046621e+05,1.232967e+06,8.693043e+05,3.586079e+05,25806.499886,1.323978
min,0.440000,8.456000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,2015.000000
25%,1.110000,1.323404e+04,8.225900e+02,3.061135e+03,0.000000e+00,7.319505e+03,4.770445e+03,2.358200e+02,0.000000,2016.000000
50%,1.360000,1.190528e+05,9.855110e+03,2.697755e+04,1.937600e+02,4.625771e+04,3.133734e+04,4.043680e+03,0.000000,2017.000000
75%,1.640000,4.733783e+05,1.141219e+05,1.498719e+05,6.078170e+03,1.394295e+05,1.008827e+05,3.050337e+04,313.890000,2018.000000
max,3.250000,6.371614e+07,2.274362e+07,2.047057e+07,2.546439e+06,2.347299e+07,1.543625e+07,7.864297e+06,844929.830000,2019.000000
Coefficient of Variation (%),27.540891,4.069319e+02,4.321886e+02,4.088332e+02,4.659181e+02,4.178938e+02,4.092386e+02,4.724790e+02,585.760726,0.065648
Variance (%),7.585007,1.655936e+03,1.867870e+03,1.671446e+03,2.170797e+03,1.746353e+03,1.674763e+03,2.232364e+03,3431.156286,0.000043

on the data where the variance is high. sicne the variation is very high, it could mean that those as feature are stronger indicators than for example average price. we will see in the corelation matrix

In [40]:
numeric_df.corr()

,AveragePrice,TotalVolume,4046,4225,4770,TotalBags,SmallBags,LargeBags,XLargeBags,year
AveragePrice,1.000000,-0.189798,-0.207419,-0.169248,-0.177540,-0.173709,-0.174233,-0.162197,-0.110087,0.022026
TotalVolume,-0.189798,1.000000,0.977791,0.968629,0.872152,0.964414,0.973372,0.874147,0.751694,0.029571
4046,-0.207419,0.977791,1.000000,0.925580,0.842456,0.918115,0.931231,0.823114,0.692580,0.007619
4225,-0.169248,0.968629,0.925580,1.000000,0.880154,0.894032,0.914190,0.779562,0.673557,-0.004632
4770,-0.177540,0.872152,0.842456,0.880154,1.000000,0.801221,0.812533,0.699417,0.681737,-0.019138
TotalBags,-0.173709,0.964414,0.918115,0.894032,0.801221,1.000000,0.991109,0.945800,0.816574,0.086012
SmallBags,-0.174233,0.973372,0.931231,0.914190,0.812533,0.991109,1.000000,0.894541,0.802051,0.073336
LargeBags,-0.162197,0.874147,0.823114,0.779562,0.699417,0.945800,0.894541,1.000000,0.756260,0.109252
XLargeBags,-0.110087,0.751694,0.692580,0.673557,0.681737,0.816574,0.802051,0.756260,1.000000,0.098239
year,0.022026,0.029571,0.007619,-0.004632,-0.019138,0.086012,0.073336,0.109252,0.098239,1.000000

In [ ]:
# univariate analysis of 'Price' column
from scipy import stats
import numpy as np

fig = px.histogram(prices_and_sales_df, x='AveragePrice', 
                   nbins=prices_and_sales_df['AveragePrice'].nunique()//10,
                   title='Distribution of Price',
                   labels={'AveragePrice': 'Price'},
                   marginal='box',
                   histnorm='probability density')

# Calculate KDE for smooth density curve
data = prices_and_sales_df['AveragePrice'].dropna()
kde = stats.gaussian_kde(data)
x_range = np.linspace(data.min(), data.max(), 200)
y_kde = kde(x_range)

fig.add_trace(go.Scatter(x=x_range, y=y_kde, 
                         mode='lines', 
                         name='Density Curve',
                         line=dict(color='red', width=2)))

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'histnorm': 'probability density',
              'hovertemplate': 'Price=%{x}<br>probability density=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'nbinsx': 25,
              'orientation': 'v',
              'showlegend': False,
              'type': 'histogram',
              'x': {'bdata': ('hetRuB6F8z8AAAAAAADwPwAAAAAAAP' ... 'NwPQrX/z+kcD0K16MCQHE9CtejcP0/'),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'hovertemplate': 'Price=%{x}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'notched': True,
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('hetRuB6F8z8AAAAAAADwPwAAAAAAAP' ... 'NwPQrX/z+kcD0K16MCQHE9CtejcP0/'),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'},
             {'line': {'color': 'red', 'width': 2},
              'mode': 'lines',
              'name': 'Density Curve',
              'type': 'scatter',
              'x': {'bdata': ('KVyPwvUo3D9a7pjcTxDdP4qAovap99' ... 'kpxglAus2+vBTjCUAAAAAAAAAKQA=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('OR3R0q1jcD8dTC134OF3P/LNMkOS0o' ... 'qX2UA/zWXjMdwgPz85AbVh+SA8Pw=='),
                    'dtype': 'f8'}}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Distribution of Price'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Price'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x', 'showgrid': True, 'showticklabels': False},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 0.8316], 'title': {'text': 'probability density'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.8416, 1.0],
                          'matches': 'y2',
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': ''}}
})

In [ ]:
# univariate analysis of 'total volume' column
from scipy import stats
import numpy as np

# I wanna show the density but the deviation is too big. so i use the count to get the density
data = prices_and_sales_df['TotalVolume'].dropna()
log_data = np.log10(data)

fig = px.histogram(x=log_data, 
                   nbins=50,
                   title='Distribution of Total Volume (Log Scale)',
                   labels={'x': 'Log10(Total Volume)'},
                   marginal='box',
                   histnorm='probability density')

# Calculate KDE
kde = stats.gaussian_kde(log_data)
x_range = np.linspace(log_data.min(), log_data.max(), 200)
y_kde = kde(x_range)

fig.add_trace(go.Scatter(x=x_range, y=y_kde, 
                         mode='lines', 
                         name='Density Curve',
                         line=dict(color='red', width=2)))

fig.update_yaxes(title_text='Density')
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'histnorm': 'probability density',
              'hovertemplate': 'Log10(Total Volume)=%{x}<br>probability density=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'nbinsx': 50,
              'orientation': 'v',
              'showlegend': False,
              'type': 'histogram',
              'x': {'bdata': ('57yaMR1yEkAMXYHA1Y0WQLyQ25YOlh' ... 'OTXhhAF5VAlLJIFUC2LYUnP9sQQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'hovertemplate': 'Log10(Total Volume)=%{x}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'notched': True,
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('57yaMR1yEkAMXYHA1Y0WQLyQ25YOlh' ... 'OTXhhAF5VAlLJIFUC2LYUnP9sQQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'},
             {'line': {'color': 'red', 'width': 2},
              'mode': 'lines',
              'name': 'Density Curve',
              'type': 'scatter',
              'x': {'bdata': ('ssyp8KrV/j8igJugok7/P5EzjVCax/' ... 'UR+x5ARqVmQU8ZH0AiEmMtjTcfQA=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('rom7zB+hID8Uxf8cujQgP1ECGKye/x' ... 'iYPIY/yk/NcsElgT8d5YfkroZ5Pw=='),
                    'dtype': 'f8'}}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Distribution of Total Volume (Log Scale)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Log10(Total Volume)'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x', 'showgrid': True, 'showticklabels': False},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 0.8316], 'title': {'text': 'Density'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.8416, 1.0],
                          'matches': 'y2',
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': '',
                          'title': {'text': 'Density'}}}
})

In [65]:
# Bivariate analysis: Average Price variation across years
fig = px.box(prices_and_sales_df, x='year', y='AveragePrice',
             title='Average Price Distribution by Year',
             labels={'year': 'Year', 'AveragePrice': 'Average Price ($)'},
             color='year',
             points='outliers')
fig.update_xaxes(type='category')
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'boxpoints': 'outliers',
              'hovertemplate': 'Year=%{x}<br>Average Price ($)=%{y}<extra></extra>',
              'legendgroup': '2015',
              'marker': {'color': '#636efa'},
              'name': '2015',
              'notched': False,
              'offsetgroup': '2015',
              'orientation': 'v',
              'showlegend': True,
              'type': 'box',
              'x': {'bdata': ('3wffB98H3wffB98H3wffB98H3wffB9' ... 'ffB98H3wffB98H3wffB98H3wffBw=='),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('hetRuB6F8z8AAAAAAADwPwAAAAAAAP' ... 'XrUfg/XI/C9Shc9z/2KFyPwvX8Pw=='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'boxpoints': 'outliers',
              'hovertemplate': 'Year=%{x}<br>Average Price ($)=%{y}<extra></extra>',
              'legendgroup': '2016',
              'marker': {'color': '#EF553B'},
              'name': '2016',
              'notched': False,
              'offsetgroup': '2016',
              'orientation': 'v',
              'showlegend': True,
              'type': 'box',
              'x': {'bdata': ('4AfgB+AH4AfgB+AH4AfgB+AH4AfgB+' ... 'fgB+AH4AfgB+AH4AfgB+AH4AfgB+AH'),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('exSuR+F68D/NzMzMzMzwP8P1KFyPwv' ... '0K16Nw9T8fhetRuB7tP/YoXI/C9fQ/'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'boxpoints': 'outliers',
              'hovertemplate': 'Year=%{x}<br>Average Price ($)=%{y}<extra></extra>',
              'legendgroup': '2017',
              'marker': {'color': '#00cc96'},
              'name': '2017',
              'notched': False,
              'offsetgroup': '2017',
              'orientation': 'v',
              'showlegend': True,
              'type': 'box',
              'x': {'bdata': ('4QfhB+EH4QfhB+EH4QfhB+EH4QfhB+' ... 'EH4QfhB+EH4QfhB+EH4QfhB+EH4Qc='),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('hetRuB6F9z/D9Shcj8LtP4XrUbgehf' ... '6F61H4P65H4XoUrvc/7FG4HoXr+T8='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'boxpoints': 'outliers',
              'hovertemplate': 'Year=%{x}<br>Average Price ($)=%{y}<extra></extra>',
              'legendgroup': '2018',
              'marker': {'color': '#ab63fa'},
              'name': '2018',
              'notched': False,
              'offsetgroup': '2018',
              'orientation': 'v',
              'showlegend': True,
              'type': 'box',
              'x': {'bdata': ('4gfiB+IH4gfiB+IH4gfiB+IH4gfiB+' ... 'fiB+IH4gfiB+IH4gfiB+IH4gfiB+IH'),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('FK5H4XoU8j9cj8L1KFzvPwAAAAAAAP' ... 'A9Ctej9D/sUbgehev5PwrXo3A9Cvs/'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'boxpoints': 'outliers',
              'hovertemplate': 'Year=%{x}<br>Average Price ($)=%{y}<extra></extra>',
              'legendgroup': '2019',
              'marker': {'color': '#FFA15A'},
              'name': '2019',
              'notched': False,
              'offsetgroup': '2019',
              'orientation': 'v',
              'showlegend': True,
              'type': 'box',
              'x': {'bdata': ('4wfjB+MH4wfjB+MH4wfjB+MH4wfjB+' ... 'fjB+MH4wfjB+MH4wfjB+MH4wfjB+MH'),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('UrgehetR8D8fhetRuB7xP3E9CtejcO' ... 'NwPQrX/z+kcD0K16MCQHE9CtejcP0/'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'boxmode': 'overlay',
               'legend': {'title': {'text': 'Year'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Average Price Distribution by Year'},
               'xaxis': {'anchor': 'y',
                         'categoryarray': [2015, 2016, 2017, 2018, 2019],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'Year'},
                         'type': 'category'},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Average Price ($)'}}}
})

In [68]:
# Bivariate analysis: Total Volume variation across years (using log scale for density)
# Create a temporary column with log-transformed volume
prices_and_sales_df_copy = prices_and_sales_df.copy()
prices_and_sales_df_copy['Log_TotalVolume'] = np.log10(prices_and_sales_df_copy['TotalVolume'])

fig2 = px.violin(prices_and_sales_df_copy, x='year', y='Log_TotalVolume',
                 title='Total Volume Distribution by Year (Log Scale Density)',
                 labels={'year': 'Year', 'Log_TotalVolume': 'Log10(Total Volume)'},
                 color='year',
                 box=True,  # Add box plot inside violin
                 points='outliers')  # Show outlier points
fig2.update_xaxes(type='category')
fig2

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'visible': True},
              'hovertemplate': 'Year=%{x}<br>Log10(Total Volume)=%{y}<extra></extra>',
              'legendgroup': '2015',
              'marker': {'color': '#636efa'},
              'name': '2015',
              'offsetgroup': '2015',
              'orientation': 'v',
              'points': 'outliers',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('3wffB98H3wffB98H3wffB98H3wffB9' ... 'ffB98H3wffB98H3wffB98H3wffBw=='),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('57yaMR1yEkAMXYHA1Y0WQLyQ25YOlh' ... 'n19RZAx8JBlSmeFEDvPi6gUdYOQA=='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': True},
              'hovertemplate': 'Year=%{x}<br>Log10(Total Volume)=%{y}<extra></extra>',
              'legendgroup': '2016',
              'marker': {'color': '#EF553B'},
              'name': '2016',
              'offsetgroup': '2016',
              'orientation': 'v',
              'points': 'outliers',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('4AfgB+AH4AfgB+AH4AfgB+AH4AfgB+' ... 'fgB+AH4AfgB+AH4AfgB+AH4AfgB+AH'),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('qQsT43SxFEA4mA9AKZwWQOtUhCf8pR' ... '78sAbYF0D6szaUcAMWQF+lhATe9RBA'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': True},
              'hovertemplate': 'Year=%{x}<br>Log10(Total Volume)=%{y}<extra></extra>',
              'legendgroup': '2017',
              'marker': {'color': '#00cc96'},
              'name': '2017',
              'offsetgroup': '2017',
              'orientation': 'v',
              'points': 'outliers',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('4QfhB+EH4QfhB+EH4QfhB+EH4QfhB+' ... 'EH4QfhB+EH4QfhB+EH4QfhB+EH4Qc='),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('crsuOIB0FEADIX+qKPQWQESzDBXEMx' ... 'AcE2EYQAAAAAAAAPh/DOEXOR/gEEA='),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': True},
              'hovertemplate': 'Year=%{x}<br>Log10(Total Volume)=%{y}<extra></extra>',
              'legendgroup': '2018',
              'marker': {'color': '#ab63fa'},
              'name': '2018',
              'offsetgroup': '2018',
              'orientation': 'v',
              'points': 'outliers',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('4gfiB+IH4gfiB+IH4gfiB+IH4gfiB+' ... 'fiB+IH4gfiB+IH4gfiB+IH4gfiB+IH'),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('Vp8W03X5E0CV/f9vImoXQGCUlE6GjB' ... 'vV+BLxDkCZqabfA7gVQH2Pxxkm4BBA'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': True},
              'hovertemplate': 'Year=%{x}<br>Log10(Total Volume)=%{y}<extra></extra>',
              'legendgroup': '2019',
              'marker': {'color': '#FFA15A'},
              'name': '2019',
              'offsetgroup': '2019',
              'orientation': 'v',
              'points': 'outliers',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('4wfjB+MH4wfjB+MH4wfjB+MH4wfjB+' ... 'fjB+MH4wfjB+MH4wfjB+MH4wfjB+MH'),
                    'dtype': 'i2'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('kloTv2iaHkAjlKdwAnIUQGVyxpiVrB' ... 'NzU5NeGEAXlUCUskgVQLYthSc/2xBA'),
                    'dtype': 'f8'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'Year'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Total Volume Distribution by Year (Log Scale Density)'},
               'violinmode': 'overlay',
               'xaxis': {'anchor': 'y',
                         'categoryarray': [2015, 2016, 2017, 2018, 2019],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'Year'},
                         'type': 'category'},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Log10(Total Volume)'}}}
})

In [ ]:
# Bivariate analysis: Every variable against every variable (Scatter Matrix)
key_features = ['AveragePrice', 'TotalVolume', '4046', '4225', '4770', 
                'TotalBags', 'SmallBags', 'LargeBags'] # can be changed to use all numeric columns

fig3 = px.scatter_matrix(prices_and_sales_df, 
                         dimensions=key_features,
                         title='Scatter Matrix: Bivariate Analysis of All Variables',
                         height=1200,
                         width=1200)

fig3.update_traces(diagonal_visible=True, showupperhalf=False)

fig3

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'diagonal': {'visible': True},
              'dimensions': [{'axis': {'matches': True},
                              'label': 'AveragePrice',
                              'values': {'bdata': ('hetRuB6F8z8AAAAAAADwPwAAAAAAAP' ... 'NwPQrX/z+kcD0K16MCQHE9CtejcP0/'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': 'TotalVolume',
                              'values': {'bdata': ('XI/C9Sj140Bcj8L1NY0aQexRuB5yDC' ... 'oULunfMkEpXI/CAZAJQYXrUbge+s9A'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': '4046',
                              'values': {'bdata': ('AAAAAAAHpkD2KFyPOTwWQbgehetpXO' ... '0K1yf4+UCuR+F6pFvXQKRwPQrXrpJA'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': '4225',
                              'values': {'bdata': ('FK5H4dqf20DXo3A9SkPXQEjhehSU3y' ... 'A9CuWcCUE9CtejALjkQM3MzMzMSIVA'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': '4770',
                              'values': {'bdata': ('MzMzMzPzSECamZmZmYlUQFyPwvVgh+' ... 'mZmRnmtUCPwvUoXM2OQIXrUbiemqVA'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': 'TotalBags',
                              'values': {'bdata': ('FK5H4Tr6wkB7FK5H+dvmQArXo3CFOg' ... 'yPwhTtK0HhehSuv1cBQcP1KFwP6cZA'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': 'SmallBags',
                              'values': {'bdata': ('pHA9CnfxwUCamZmZyVDQQPYoXI/QvQ' ... '5H4c1eJEFI4XoUsobyQNejcD2qNsVA'),
                                         'dtype': 'f8'}},
                             {'axis': {'matches': True},
                              'label': 'LargeBags',
                              'values': {'bdata': ('CtejcD2MgEBcj8L1KGfdQB+F61E4La' ... 'AAAFI4DkHXo3A9OifwQLgehetRJotA'),
                                         'dtype': 'f8'}}],
              'hovertemplate': '%{xaxis.title.text}=%{x}<br>%{yaxis.title.text}=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'name': '',
              'showlegend': False,
              'showupperhalf': False,
              'type': 'splom'}],
    'layout': {'dragmode': 'select',
               'height': 1200,
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Scatter Matrix: Bivariate Analysis of All Variables'},
               'width': 1200}
})

In [72]:
# Heatmap of Correlation Matrix
correlation_matrix = numeric_df.corr()

fig4 = px.imshow(correlation_matrix,
                labels=dict(x="Features", y="Features", color="Correlation"),
                x=correlation_matrix.columns,
                y=correlation_matrix.columns,
                color_continuous_scale='RdBu_r',  # Red for positive, Blue for negative
                zmin=-1,
                zmax=1,
                title='Correlation Matrix Heatmap',
                text_auto='.2f',  # Show correlation values with 2 decimal places
                aspect='auto')

fig4.update_layout(width=900, height=800)
fig4

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'coloraxis': 'coloraxis',
              'hovertemplate': 'Features: %{x}<br>Features: %{y}<br>Correlation: %{z}<extra></extra>',
              'name': '0',
              'texttemplate': '%{z:.2f}',
              'type': 'heatmap',
              'x': array(['AveragePrice', 'TotalVolume', '4046', '4225', '4770', 'TotalBags',
                          'SmallBags', 'LargeBags', 'XLargeBags', 'year'], dtype=object),
              'xaxis': 'x',
              'y': array(['AveragePrice', 'TotalVolume', '4046', '4225', '4770', 'TotalBags',
                          'SmallBags', 'LargeBags', 'XLargeBags', 'year'], dtype=object),
              'yaxis': 'y',
              'z': {'bdata': ('AAAAAAAA8D/HqUwbTkvIv6heqEu4jM' ... 'oD7Pe7P8EgEu80Jrk/AAAAAAAA8D8='),
                    'dtype': 'f8',
                    'shape': '10, 10'}}],
    'layout': {'coloraxis': {'cmax': 1,
                             'cmin': -1,
                             'colorbar': {'title': {'text': 'Correlation'}},
                             'colorscale': [[0.0, 'rgb(5,48,97)'], [0.1,
                                            'rgb(33,102,172)'], [0.2,
                                            'rgb(67,147,195)'], [0.3,
                                            'rgb(146,197,222)'], [0.4,
                                            'rgb(209,229,240)'], [0.5,
                                            'rgb(247,247,247)'], [0.6,
                                            'rgb(253,219,199)'], [0.7,
                                            'rgb(244,165,130)'], [0.8,
                                            'rgb(214,96,77)'], [0.9,
                                            'rgb(178,24,43)'], [1.0,
                                            'rgb(103,0,31)']]},
               'height': 800,
               'template': '...',
               'title': {'text': 'Correlation Matrix Heatmap'},
               'width': 900,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Features'}},
               'yaxis': {'anchor': 'x', 'autorange': 'reversed', 'domain': [0.0, 1.0], 'title': {'text': 'Features'}}}
})

In [ ]:
# Find and deal with missing values